### ISSUE TITLE
Error compiling the Specan

### ISSUE THREAD

**Issue by RChadwick7** [ea/srxe_cc1101#12]
While compiling, I get this error:
'SRXEHorizontalLine' was not declared in this scope

I installed the CC1101, and SmartResponseXE libraries. What am I missing?

**Comment by ea** [comment]
There's a version of SmartResponseXE library in my repositories that contains a small patch that makes drawing bars for spectrum analyzer better and also changes the contrast a bit so it's easier to see: 
https://github.com/ea/SmartResponseXE

**Comment by RChadwick7** [comment]
That was my mistake. I thought I did use your library, but when I checked again, it was a few bytes off. It compiles great with the proper library. Thanks!
