### ISSUE TITLE
Arudino Pro MINI / OLED/ CC1101 and POCSAG pager

### ISSUE THREAD

**Issue by sp2ong** [ea/srxe_cc1101#6]
Hi,

I am very happy that I found your project. For a long time, I search who will try use CC1101 and Arduino to create low-cost DAPNET PAGER POCSAG.

It will be nice to create code for Arduino Mini Pro which will be connected to CC1101 and  0.96" SSD1306 OLED, maybe add a buzzer to announce incoming message, and we can use a battery from phone mobile  Li-ION 3.7V
It will be mont on universal board and very easy to for most hamradio operators
Would you be able to write this code for arduino?

**Comment by leon-uhs** [comment]
I am also very interested in this and the raw materials are easily available.
