### ISSUE TITLE
Operating system

### ISSUE THREAD

**Issue by ea3iav** [ea/srxe_cc1101#8]
Hello! From which OS are you performing all your steps? 
In the bootloader installation you use two commands. I wonder if those cam be executed from macOS terminal

Thank you

**Comment by ea** [comment]
The bootloader flashing commands should work on both linux and macOS with no modifications, provided `avrdude` is installed , just substitute the path to `avrdude` from `/bin/avrdudre` to wherever it is located on your platform.
