### ISSUE TITLE
Arduino sketch upload

### ISSUE THREAD

**Issue by teintuc** [ea/srxe_cc1101#9]
Hi!

First thanks for this project. I wanted to do it since a while :)

I followed the instructions and I'm at the moment where I have to upload the sketch. I'm using the arduino IDE.
I don't understand when I have to press '2' to get the firmware from serial0.
When I do, serial0 doesn't wait and I the folowing from avrdude.

`avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
`
I'm using the power from my usb to serial adapter. Might be it is wrong since it is 5v ? not 3.3 

Thanks for your help

**Comment by ea** [comment]
Timing this can be a bit tricky. What seems to work for me is, with everything connected, run avrdude as it will retry a couple of times, and then press option 2 to load firmware over serial. Let me know if doing it that way works for you. 

Cheers!

**Comment by teintuc** [comment]
Ok, my mistake.
I tried what you said and got the same result. After checking my wiring 3 times, I just reversed RX/TX and it worked.
I thought I had to reverse them in order to make it work. live and learn :)

Thanks again for this build
